sudo: required
language: generic
services:
   - docker
   
before_install:
   - docker build -t kirti2323/docker-react -f Dockerfile.dev .
   
script:
   - docker run -e CI=true kirti2323/docker-react npm run test